### ISSUE TITLE
AssertionError: Invalid port format, aborting.

### ISSUE THREAD

**Issue by markmeany** [compose-viz/compose-viz#38]
If the host port is not defined in port mapping the above error is generated.

Example:
```
version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - ":8080"
    command:
      - "start-dev"
```
